#!/usr/bin/env bash
echo "== deploy s3 bucket via CFN"

# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy.html

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-east-1 \
--stack-name $STACK_NAME

