# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html
AWSTemplateFormatVersion: 2010-09-09
Description: A sample S3 bucket.

# https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html#aws-resource-s3-bucket--examples
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
  # we don't need supply a Bucket Name as AWS will generate a random name for us